"""Generate and publish a sample movie for website preview."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

from studio.tools.generate_sample_video import generate_sample_video
from studio.website.publisher import MovieData, MoviePublisher


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate + publish sample movie")
    p.add_argument("--website_dir", default="website")
    p.add_argument("--movie_id", default="sample-prototype")
    p.add_argument("--title", default="Movilizer Prototype")
    p.add_argument("--output_video", default="outputs/sample_prototype.mp4")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    video_path = generate_sample_video(
        output=Path(args.output_video),
        fps=24,
        seconds=3.0,
        width=640,
        height=360,
    )

    publisher = MoviePublisher(website_dir=Path(args.website_dir))
    movie = MovieData(
        id=args.movie_id,
        title=args.title,
        synopsis="Synthetic prototype movie generated by Movilizer.",
        genre="Demo",
        duration_seconds=3,
        rating=4.8,
        generated_at=datetime.now(timezone.utc).isoformat(),
        thumbnail_url="",
        video_url="",
        metadata={"pipeline": "sample_video_tool"},
    )

    ok = publisher.publish_movie(movie_data=movie, video_path=video_path)
    if not ok:
        raise SystemExit(1)

    print(f"Published {args.movie_id} into {Path(args.website_dir).resolve()}")


if __name__ == "__main__":
    main()
